### ISSUE TITLE
isNotCopula shouldn't take predicate as input parameter

### ISSUE THREAD

**Issue by venkatasg** [hltcoe/PredPatt#12]
Currently the filter isNotCopula takes a predicate object as input parameter and returns True if the predicate passed doesn't have gov_rel as cop, or if it is a list of copula verbs. However this filter isn't useful, since PredPatt doesn't annotate copula verbs as predicates(because UD uses the cop relation only for pure copulas, that is when the nonverbal predicate is the head of the clause).

isNotCopula should take Token as input parameter, and the the function should use `token.gov_rel` and `token.text` instead of `pred.root.gov_rel` and `pred.root.text`.

**Comment by sheng-z** [comment]
Thanks for pointing this out. Those filters were meant to be example usage for linguistic analysis, and are a little out-dated. 
A simple modification here is still passing a `pred` object as input parameter, but instead of checking `pred.root`, you checking if any of `pred.root.dependents` is a copula verb.

Fork and PR are welcome :)

**Comment by venkatasg** [comment]
Yeah that's a good idea. I just made some changes and submitted a PR.

**Comment by venkatasg** [comment]
There is one issue with the PR which was merged. Sometimes the copula verb can be the root of the sentence, in which case the current function won't capture it. The earlier version of checking if `pred.root.text` is in `copula_verbs` should remain as an additional if condition, this will capture those as well.
